### ISSUE TITLE
unable to rub command with --long-name style

### ISSUE THREAD

**Issue by qunying** [kburtch/SparForte#3]
When running a command with --long-name style, I will get the following:
```
ls --version
End of File
^---------^ shell word or semi-colon expected
```

Tested under Slackware64, running 1.5.1 and the latest 20a3fa345.

**Comment by kburtch** [comment]
Hi,

"--" is a comment in SparForte.  The long option must be in quotes or
use backslahes for the minus signs.

=> ls "--version"
=> ls \-\-version

For more information, please read "Why do I get an error when I run a
command with a long option on the command prompt?" in the FAQ.

Thanks.
Ken B.

On 06/10/2015 6:35 PM, Zhu Qun-Ying wrote:
> When running a command with --long-name style, I will get the following:
> 
> |ls --version End of File ^---------^ shell word or semi-colon expected |
> 
> Tested under Slackware64, running 1.5.1 and the latest 20a3fa3
> <https://github.com/kburtch/SparForte/commit/20a3fa3454275c54fa82f2844c5ce0405be5b376>.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kburtch/SparForte/issues/3>.
> 

-- 
-----------------------------------------------------------------------------
Ken O. Burtch                                    Phone/Fax: 905-562-0848
  "Linux Shell Scripting with Bash"              Email: ken@pegasoft.ca
-----------------------------------------------------------------------------

**Comment by qunying** [comment]
Sorry. I was suspecting my end of error but did not dig dipper to the FAQ.  Problem solved.
